---
title: "iris dataset exploration"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GitHub Documents

This is an R Markdown format used for publishing markdown documents to GitHub. When you click the **Knit** button all R code chunks are run and a markdown file (.md) suitable for publishing to GitHub is generated.

## Including Code

You can include R code in the document as follows:

```{r iris data}
library(caret)
data(iris)
iris <- iris[-which(iris$Species=='setosa'),]
y <- iris$Species

```
```{r splitting the dataset between train and test}



set.seed(2, sample.kind="Rounding")    # if using R 3.6 or later, use set.seed(2, sample.kind="Rounding")
test_index <- createDataPartition(y,times=1,p=0.5,list=FALSE)
test <- iris[test_index,]
train <- iris[-test_index,]


cutoff <- seq(1, 10,0.1)
cutoff
```

```{r}

#accuracy for sepal.Width
library(purrr)
accuracy <- map_dbl(cutoff, function(x){
  y_hat <- ifelse(train$Sepal.Width > x, "virginica", "versicolor")
  mean(y_hat == train$Species)
})

max(accuracy)

#accuracy for sepal.length

accuracy <- map_dbl(cutoff, function(x){
  y_hat <- ifelse(train$Sepal.Length > x, "virginica", "versicolor")
  
  mean(y_hat == train$Species)
})

max(accuracy)

#accuracy for Petal.Width

accuracy <- map_dbl(cutoff, function(x){
  y_hat <- ifelse(train$Petal.Width > x, "virginica", "versicolor")
  mean(y_hat == train$Species)
})

max(accuracy)

#accuracy for Petal.Length

accuracy <- map_dbl(cutoff, function(x){
  y_hat <- ifelse(train$Petal.Length > x, "virginica", "versicolor")
  mean(y_hat == train$Species)
})

max(accuracy)
```

```{r}
#applying the training cutoff for test data

best_cutoff <- cutoff[which.max(accuracy)]
best_cutoff
y_hat <- ifelse(test$Petal.Length > best_cutoff, "virginica", "versicolor") 

mean(y_hat == test$Species)
```
```{r}
#lets do some data exploratory analysis

plot(iris,pch=21,bg=iris$Species)
```


