---
title: "knn algorithm vs logistic regression"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## code for knn algorithm.

You can include R code in the document as follows:
```{r}
library(tidyverse)
library(dslabs)
library(caret)
data("mnist_27")
```

```{r sample knn code}

x <- as.matrix(mnist_27$train[,2:3])
y <- mnist_27$train$y
knn_fit <- knn3(x,y)
```
```{r logistic regression for mnist dataset}
library(caret)
fit_glm<-glm(y~x_1+x_2,data = mnist_27$train,family="binomial")
p_hat_logistic <- predict(fit_glm, mnist_27$test)
y_hat_logistic <- ifelse(p_hat_logistic>0.5,7,2)%>%factor
length(y_hat_logistic)
length(mnist_27$test$y)
confusionMatrix(data = y_hat_logistic, reference = mnist_27$test$y)$overall[1]

```
```{r}
#make the predictors (features) as matrix
x <- as.matrix(mnist_27$train[,2:3])
#make outcomes as a vector
y <- mnist_27$train$y
#one way to call knn 
knn_fit <- knn3(x, y)
#another way to call knn
knn_fit <- knn3(y ~ ., data = mnist_27$train, k=5)


y_hat_knn<-predict(knn_fit, mnist_27$test, type = "class")
length(y_hat_knn)
length(mnist_27$test$y)
confusionMatrix(data = y_hat_knn, reference = mnist_27$test$y)$overall["Accuracy"]
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
