---
title: "knn algorithm vs logistic regression"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## code for knn algorithm.

You can include R code in the document as follows:
```{r}
library(tidyverse)
library(dslabs)
library(caret)
data("mnist_27")
```

```{r sample knn code with k}

#make the predictors (features) as matrix
x <- as.matrix(mnist_27$train[,2:3])
#make outcomes as a vector
y <- mnist_27$train$y
#one way to call knn 
#another way to call knn
k<-5

#train_fitt and accuracy -- this is not required but just to show the sample
knn_fit <- knn3(y ~ ., data = mnist_27$train, k=k)
knn_fit

y_hat_knn<-predict(knn_fit, mnist_27$train, type = "class")
train_accuracy<-confusionMatrix(data = y_hat_knn, reference = mnist_27$train$y)$overall["Accuracy"]
k
train_accuracy
#test_fitting and accuracy
knn_fit <- knn3(y ~ ., data = mnist_27$train, k=k)

y_hat_knn<-predict(knn_fit, mnist_27$test, type = "class")
length(y_hat_knn)
length(mnist_27$test$y)
k
test_accuracy<-confusionMatrix(data = y_hat_knn, reference = mnist_27$test$y)$overall["Accuracy"]
test_accuracy

```

```{r k401 value}
k<-401

#train_fitt and accuracy -- this is not required but just to show the sample
knn_fit <- knn3(y ~ ., data = mnist_27$train, k=k)

y_hat_knn<-predict(knn_fit, mnist_27$train, type = "class")
train_accuracy<-confusionMatrix(data = y_hat_knn, reference = mnist_27$train$y)$overall["Accuracy"]
k
train_accuracy
#test_fitting and accuracy
knn_fit <- knn3(y ~ ., data = mnist_27$train, k=k)

y_hat_knn<-predict(knn_fit, mnist_27$test, type = "class")
length(y_hat_knn)
length(mnist_27$test$y)
k
test_accuracy<-confusionMatrix(data = y_hat_knn, reference = mnist_27$test$y)$overall["Accuracy"]
test_accuracy
```

```{r generating accuracy for multiple ks}
#pick the k in knn
ks <- seq(3, 251, 2)
library(purrr)
accuracy <- map_df(ks, function(k){
    fit <- knn3(y ~ ., data = mnist_27$train, k = k)
    y_hat <- predict(fit, mnist_27$train, type = "class")
    cm_train <- confusionMatrix(data = y_hat, reference = mnist_27$train$y)
    train_error <- cm_train$overall["Accuracy"]
    y_hat <- predict(fit, mnist_27$test, type = "class")
    cm_test <- confusionMatrix(data = y_hat, reference = mnist_27$test$y)
    test_error <- cm_test$overall["Accuracy"]
    
tibble(train = train_error, test = test_error)
    })


#pick the k that maximizes accuracy using the estimates built on the test data
ks[which.max(accuracy$test)]
max(accuracy$test)

```

```{r}
qqplot(ks,accuracy$test)
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
